version: '3.8'

services:
  react-project-dev:
    container_name: react-project-container_name
    image: react-project-dev-image
    build:
      context: . 
      dockerfile: Dockerfile.dev  # Use the dev Dockerfile created
    volumes:
      - .:/bun                     # Mount the project directory for live reload
      - /bun/node_modules           # Ignore node_modules (managed by Bun)
    ports:
      - "5173:5173"                 # Map Vite's default dev port to localhost
    environment:
      - CHOKIDAR_USEPOLLING=true    # Ensures hot-reload works well in Docker

    command: bun run dev            # Run the dev server using Bun
